version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-shop-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: python run.py

  webapp:
    build: .
    container_name: telegram-shop-webapp
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    command: gunicorn -w 4 -b 0.0.0.0:8080 webapp.app:app
